spring:
    jpa:
        hibernate:
          ddl-auto: update
        properties:
            hibernate:
                temp:
                  use_jdbc_metadata_defaults: false
                show_sql: true
                jdbc:
                    lob:
                        non_contextual_creation: true
        generate-ddl: true
        database: postgresql
    datasource:
#        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost/sarafan
        username: admin
        password: q1w2e3
    main:
      allow-bean-definition-overriding: true

security:
  oauth2:
    client:
      clientId: 578485243240-k48i80t9tj2h8r6s8tmoitg1e9pm154f.apps.googleusercontent.com
      clientSecret: MDAa7Bdp7j8DX2Jugs75rccS
      authentication-scheme: form
      scope: openid,email,profile
      access-token-uri: https://www.googleapis.com/oauth2/v4/token
      user-authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
    resource:
      user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
      prefer-token-info: true